# Generated by Django 3.1.3 on 2022-03-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertab',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='usertab',
            name='picture',
        ),
    ]
