# Generated by Django 3.1.3 on 2022-03-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20220322_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=49)),
                ('username', models.CharField(max_length=49)),
                ('filename', models.CharField(max_length=149)),
                ('filetitle', models.CharField(max_length=149)),
                ('access', models.CharField(max_length=149)),
                ('filedata', models.TextField()),
                ('stz', models.CharField(max_length=14)),
            ],
        ),
    ]
