# Generated by Django 3.1.3 on 2022-03-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_scpattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=49)),
                ('user', models.CharField(max_length=49)),
                ('sc_calls', models.TextField()),
                ('datetime', models.CharField(max_length=49)),
                ('hostaddr', models.CharField(max_length=249)),
                ('ipaddr', models.CharField(max_length=49)),
                ('intruder', models.CharField(max_length=149)),
                ('stz', models.CharField(max_length=49)),
            ],
        ),
    ]
